### ISSUE TITLE
1.1.0 triggered false positive for $::settings::ssldir

### ISSUE THREAD

**Issue by baurmatt** [voxpupuli/puppet-lint-topscope-variable-check#15]
We have such a code:

```puppet
class foo (
) {
  ...
  $ssldir = $::settings::ssldir
  ...
}
```

IMHO this is correct and a valid use case for topscope variables. Since version 1.1.0 this is marked as an error.

**Comment by ekohl** [comment]
Shouldn't it simply be `$settings::ssldir`? I'm not sure you ever need `$::` in Puppet 4+ only code.
